# https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html
set (CMAKE_SYSTEM_NAME Windows)
set (CMAKE_SYSTEM_PROCESSOR ARM64)
set (triple aarch64-w64-mingw32)
set (CMAKE_C_COMPILER ${triple}-clang)
set (CMAKE_CXX_COMPILER ${triple}-clang++)
set (CMAKE_RC_COMPILER ${triple}-windres)
set (CMAKE_DLLTOOL ${triple}-dlltool)
set (CMAKE_ADDR2LINE ${triple}-addr2line)
set (CMAKE_AR ${triple}-ar)
set (CMAKE_NM ${triple}-nm)
set (CMAKE_OBJCOPY ${triple}-objcopy)
set (CMAKE_OBJDUMP ${triple}-objdump)
set (CMAKE_RANLIB ${triple}-ranlib)
set (CMAKE_READELF ${triple}-readelf)
set (CMAKE_STRIP ${triple}-strip)
set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Statically link CRT
set (CMAKE_C_FLAGS "--start-no-unused-arguments -Wl,-Bstatic -lunwind -Wl,-Bdynamic --end-no-unused-arguments")
set (CMAKE_CXX_FLAGS "--start-no-unused-arguments -static-libstdc++ -Wl,-Bstatic -lunwind -Wl,-Bdynamic --end-no-unused-arguments")
