Import('env')

env = env.Clone()

env.Replace(CPPDEFINES = [
])

env.Replace(CCFLAGS = [
    '-O0',
    '-gstabs3',
])

env.Program(
    target = 'test',
    source = [
        'test.c',
        'exchndl2.cxx',
    ],
)

env.Program(
    target = 'testcpp',
    source = [
        'testcpp.cxx',
        'exchndl2.cxx',
    ],
)
