#include <windows.h>
#include <ntverp.h>

#undef VER_COMPANYNAME_STR
#undef VER_PRODUCTNAME_STR
#undef VER_PRODUCTVERSION
#undef VER_PRODUCTVERSION_STR
#undef VER_DEBUG

#define VER_COMPANYNAME_STR      "Jose Fonseca"
#define VER_LEGALCOPYRIGHT_YEARS "2002-2015"
#define VER_LEGALCOPYRIGHT_STR   "Copyright " VER_LEGALCOPYRIGHT_YEARS " " VER_COMPANYNAME_STR
#define VER_PRODUCTNAME_STR      "Dr. Mingw"

#ifndef PACKAGE_VERSION_MAJOR
#error PACKAGE_VERSION_MAJOR
#endif
#ifndef PACKAGE_VERSION_MINOR
#error PACKAGE_VERSION_MINOR
#endif
#ifndef PACKAGE_VERSION_PATCH
#error PACKAGE_VERSION_PATCH
#endif

#define VER_PRODUCTVERSION_MAJORMINORPATCH2(x, y, z) #x "." #y "." #z
#define VER_PRODUCTVERSION_MAJORMINORPATCH1(x, y, z) VER_PRODUCTVERSION_MAJORMINORPATCH2(x, y, z)

#define VER_PRODUCTVERSION PACKAGE_VERSION_MAJOR, PACKAGE_VERSION_MINOR, PACKAGE_VERSION_PATCH, 0
#define VER_PRODUCTVERSION_STR \
    VER_PRODUCTVERSION_MAJORMINORPATCH1(PACKAGE_VERSION_MAJOR, PACKAGE_VERSION_MINOR, \
                                        PACKAGE_VERSION_PATCH)

#ifdef NDEBUG
#define VER_DEBUG 0
#else
#define VER_DEBUG VS_FF_DEBUG
#endif

#define VER_FILETYPE    VFT_DLL
#define VER_FILESUBTYPE VFT2_UNKNOWN

#include <common.ver>
